### ISSUE TITLE
For consideration: Famo.us

### ISSUE THREAD

**Issue by Dharmoslap** [tastejs/todomvc#1063]
Hi,

would there be anyone interested in an implementation of TodoMVC in Famo.us? 
Please let me know.

Best regards,
Ladislav

**Comment by arthurvr** [comment]
>  I would try both vanilla Famo.us and Famo.us/Angular.

IMHO one example should be enough.

**Comment by arthurvr** [comment]
Whoops. Sorry :)

**Comment by arthurvr** [comment]
There has been quite a bit of noise around the new framework they're developing: https://github.com/Famous/framework. Although I do not know if its community is yet mature enough for us to include a new example written with it.

**Comment by samccone** [comment]
ping @TheAlphaNerd

**Comment by TheAlphaNerd** [comment]
So I think it is quite pre mature to do anything with Framework. That being said our engine went through a major overhaul since the propertycross example, so much so that their example uses an entirely deprecated API.

I don't know if we would want to focus internal resources on implementing this at the current time, but we would definitely code review and offer a canonical opinion on anything submitted.

**Comment by arthurvr** [comment]
> So I think it is quite pre mature to do anything with Framework.

Few months later, what's the status of Framework?

**Comment by Dharmoslap** [comment]
Garbage collected https://techcrunch.com/2015/11/06/nopen-source/
