### ISSUE TITLE
Update Wanted: Ember

### ISSUE THREAD

**Issue by passy** [tastejs/todomvc#1069]
The app is on Ember 1.6.1, the latest is 1.9.0-beta.3. Additionally, we're on ember-data#1.0.0-beta.7 (latest is 1.0.0-beta.11). I believe the latter has some breaking changes.

Anyone up for this? :)

**Comment by nikolas** [comment]
I agree @phillipsj, ember-cli should be a different application in TodoMVC. It's still valuable to have the existing ember.js application up because there's still use cases for people wanting to set an Ember app up the more traditional, manual way.

For example, I'm making a Django application and I want the Ember application to be defined in a Django template. In that case, it seems to make more sense to not use ember-cli. I like using ember-cli when it's appropriate, though.

**Comment by arthurvr** [comment]
Regarding ember CLI, I personally think it's out of scope for TodoMVC. Ember CLI isn't about an MV* framework anymore. It's about the build script and developer tooling used for building apps, with a specific framework.

So, I'd personally say we should just update to the latest ember but an Ember CLI app is out of scope. Though, maybe somebody should just kick off an app in a separated repo. What does the rest think?

**Comment by iheanyi** [comment]
So we're in agreement that there needs to be a completely separate ember-cli example, then? Really interested in this, so just wanna make sure. :)

**Comment by samccone** [comment]
yep! @iheanyi I think a great initial thing to start with would be

https://github.com/ember-cli/ember-cli-todos

open a a PR and we can go from there.. thanks a million :revolving_hearts:

**Comment by samccone** [comment]
DONE!
