### ISSUE TITLE
Drop Maria and Agility

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1173]
https://github.com/arturadib/agility/releases
Latest Release: on Sep 3, 2012

https://github.com/petermichaux/maria/releases
Latest Release: on Jul 25, 2013

**Comment by sindresorhus** [comment]
I dropped `agility`.

:+1: to Maria too, but gonna wait on @tastejs/todomvc feedback.

**Comment by passy** [comment]
:+1: for both

**Comment by arthurvr** [comment]
:+1: I think we agree on this, so can I go ahead and drop `maria`?

**Comment by samccone** [comment]
:+1:

**Comment by addyosmani** [comment]
:+1:

**Comment by petermichaux** [comment]
I'm sorry to see you've decided to drop Maria. I don't know why you would given the current status of the Maria project. It is feature complete and super stable with no bugs being reported. It is fully documented.  It works in a very wide variety of browsers including legacy browsers. It is in use in production by multiple companies. There are many more likes for Maria than Ampersand or Troup which are both still listed on the TodoMVC page.

**Comment by arthurvr** [comment]
Hey @petermichaux! Thanks for jumping into the discussion. I think we dropped it for various reasons:

* The app does not have an active maintainer. We kind of need somebody to take care of stuff. https://github.com/tastejs/todomvc/issues/1110 and https://github.com/tastejs/todomvc/pulls?q=is%3Apr+author%3Apetermichaux+is%3Aclosed as a proof.
* Its commit log has some activity, but can't be consider really active IMHO.
* Its latest release was _Jul 25, 2013_, that's quite long ago.
* The sign that nobody complained about it in this issue expect you (after nearly 2 months).

Anyways, I'm glad you joined the discussion and reconsidering it can't hurt. @tastejs/todomvc What does the rest think? I still think we made the right decision.

**Comment by petermichaux** [comment]
The Maria project will see more activity eventually around documentation but it will likely never appear to be highly active project. The code base is complete: it has Model, View, and Controller classes. It does not receive any bug reports even though it is use under quite different requirements. The ability to plugin to Maria for extensibility was a primary design consideration. Isn't that the dream-come-true situation for anyone building an app on top of a framework? The framework is feature-complete, apparently bug free, stable, and extensible. That is what I want from a framework. :)

**Comment by ColinEberhardt** [comment]
@petermichaux I am sure Maria is a great MVC framework and you clearly have put a lot of effort into it.

However ... it just doesn't look like it is that widely used. I can't see any issues that were raised this year. You could take this as a sign that the project is mature and bug-free. However, it is more likely an indication that it isn't being used much. Any popular framework will get a number of issues raised by new users asking questions, submitting ideas, falsely claiming bugs etc ... This is the sign of a popular project (even if it can be a pain to keep up with all the correspondence!).

I agree, this was the right decision.

**Comment by samccone** [comment]
Looks like @addyosmani is getting a bit of feedback on twitter about this as well
https://twitter.com/varjs/status/585348217711284224

would love to hook everyone in to this discussion

**Comment by arthurvr** [comment]
I also totally agree with what @addyosmani said on twitter. Calling a framework (or basically any piece of software) _"bug free"_ or even _"finished"_ is simply wrong. There are always improvements possible, and given the amount of bug reports other frameworks get, I think the lack of bug reports is more likely due to it being less/not popular.

At the moment, I also believe this was the right decision.

**Comment by addyosmani** [comment]
One of the core goals of the project is to educate and inform developers of mature, production ready and unique solutions for building apps. Maria fell squarely in this bucket when we first landed it. 

I'll reiterate that no framework should consider itself 'finished'. Even if the core solution is feature complete (e.g Backbone 1.0), you will almost certainly see bug reports and feature requests as a result of users using your solution. 

Our analysis of Maria's tracker indicates that as a result of not growing in use (no ones fault and not an indication of Engineering quality which we know to be high), it doesn't make sense for us to continue recommending it. If there are users of Maria that feel strongly otherwise I would love to hear from them.

We definitely want to make sure this is a fair and sensible removal.

**Comment by jamesladd** [comment]
Removing Maria MVC's Todo example is setting a bad example, please bring it back.

As I understand it you removed the example because Maria MVC is marked as finished or hasn't had updates in a few years. That's because it works and for the set of usecases it addresses it has resolved known bugs.

So the more solid the code the more likely you are to remove it in favour of less solid bug ridden code?
This is ludicrous.

It may not be the flavour of the month nor the go to tool of Ninja Rockstar 10x programmers but
solid and working code should be celebrated and promoted.

I have used Maria MVC in production on several occasions and it is simply fantastic. Simple, clean and most of all complete and bug free. The fact it doesn't have lots of updates is a winning proposition.

Why is the TodoMVC examples a popularity contest?

**Comment by mastxxr** [comment]
Bring it back!!! It's a shame it's not in todomvc anymore! Shit frameworks can stay here but the good builded framework maria cant! Not the way to go, taste-fucking-js!

**Comment by arthurvr** [comment]
@mastxxr That's definitely not the right conduct when you want us to reconsider our decision.

**Comment by hubertlepicki** [comment]
I would like to point something else out: I frequently use TodoMVC as a way to discover new,and/or interesting frameworks/libraries. I might not end up using those, but it is great to have a site to compare solutions.

Maria MVC certainly is an interesting framework. I never used it and probably not going to use it, but seeing how the classical MVC architecture can be implemented is valuable. You can discover many of the same ideas mapped throughout other frameworks, such as Ember.

It certainly does look like Maria MVC has small community. But it is interesting from learning point of view, and an example on TodoMVC would make a lot of people discover it.

**Comment by petermichaux** [comment]
Just to ensure history doesn't record me inaccurately, I didn't and don't claim that Maria is bug free. I can't know that. She is "apparently bug free."

**Comment by stephenplusplus** [comment]
I believe the reasons the framework was removed were valid, and I also see the value in keeping it. I just wanted to quickly touch on the educational relationship between Maria and TodoMVC. If you were to look at my contributions to OSS, it's mostly aimed towards trying to make the increasingly complicated tools we use less intimidating. However, I think there's a line to be drawn for *how* TodoMVC wants to meet these goals.

In my opinion, our educational concern should be helping users decide on a framework to use for their app. I don't think TodoMVC should be concerned with educating users on design patterns (via implementations), themselves. Our own Addy has written countless blog posts and even a book strictly for this, where Maria was given a nod.

**Comment by jamesladd** [comment]
Yes it isn't the right conduct.
I guess it's fallout from finding out just now what seems to be a criteria for keeping or removing a project - which in my view is flawed

**Comment by jamesladd** [comment]
Very well put - I wish I used those words

**Comment by ColinEberhardt** [comment]
> I guess it's fallout from finding out just now what seems to be a criteria for keeping or removing a project - which in my view is flawed

The problem is there isn't a 'criteria' - if there were it would be a bit easier. Inclusion isn't based on GitHub star count, or any other metric that would make it easy to derive a precise set of criteria.

Inclusion or exclusion is the result of (healthy) debate - as is the case here.
