### ISSUE TITLE
React Example Node Leak

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1332]
##### Steps  to reproduce
- start timeline profiler
  - add three todos
  - delete three todos
  - (repeat above 2 more times)
- force GC
- stop timeline profiler

![screen shot 2015-06-06 at 8 38 15 pm](https://cloud.githubusercontent.com/assets/883126/8022113/237dc1e6-0c8c-11e5-8ed2-215d84381129.png)

---

It seems like one event listener is not getting unbound, this seems like a leak. :fountain:

**Comment by samccone** [comment]
ping @petehunt @chenglou

**Comment by chenglou** [comment]
Event listener? Afaik there are only react event listeners in there and they're all released correctly. Maybe it's something else?

**Comment by samccone** [comment]
Hi @chenglou thanks for getting back.

One thing that seems suspicious to me is the fact that once I started my test steps an event listener was  bound and then never released even after a forced GC. Is this expected?

**Comment by samccone** [comment]
After a new round of profiling @chenglou and warming the initial render state (adding and removing one todo) before starting my tests I am confident that there is a leak in this example.



Note how the heap size increases and I have a whole bunch of new ReactElements between each test:
![screen shot 2015-06-24 at 5 49 19 pm](https://cloud.githubusercontent.com/assets/883126/8344666/84194366-1a99-11e5-9bf2-4f3d051a0d3b.png)


Also each time I go through the steps of my test I end up with more nodes each run:

![screen shot 2015-06-24 at 5 51 13 pm](https://cloud.githubusercontent.com/assets/883126/8344691/abac7632-1a99-11e5-98e5-82d4eb5fc11a.png)

Based on this information I am quite confident there is a leak in this example (unless there is some caching behavior that can be accounted for)


Let me know if I can be of any more help

**Comment by spicyj** [comment]
If you add some todos and remove them before taking the first snapshot, you shouldn't see the listener. This is because React adds a single top-level listener for each event used and some events are not used except by the `<TodoItem />` component. I can't repro the HTML elements you're seeing. I get this:

![image](https://cloud.githubusercontent.com/assets/6820/8453517/ba70fbb4-1ff5-11e5-8924-298d5172b939.png)

The new ReactElements in the heap snapshot are there because each time you call render, new elements are allocated – but the old ones that they replace are freed, so there shouldn't be a real leak.

**Comment by samccone** [comment]
Hey @spicyj thanks for getting back to me, I agree there is no listener leak that was a mistake on my part. As far as the ReactElement issue, I have codified the process here https://github.com/tastejs/todomvc/pull/1368

and am still seeing a growth over time, let me know if this expected or if I have missed something. Thanks again for your time!

**Comment by flashdesignory** [comment]
Closing since React was updated https://github.com/tastejs/todomvc/pull/2202
