### ISSUE TITLE
Vue Memory Leaks

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1354]
##### Steps  to reproduce
- start timeline profiler
  - add three todos
  - delete three todos
  - (repeat above 2 more times)
- force GC
- stop timeline profiler

---

It looks like there is a DOM Node leak, based on my research it looks like there is something off about what is happening in Directive 

![screen shot 2015-06-24 at 5 38 46 pm](https://cloud.githubusercontent.com/assets/883126/8344552/f6540f3a-1a97-11e5-84b9-c579a53813fb.png)

![screen shot 2015-06-24 at 5 19 43 pm](https://cloud.githubusercontent.com/assets/883126/8344522/9fbe6eae-1a97-11e5-98ef-1cd84bb37d43.png)
![screen shot 2015-06-24 at 5 19 36 pm](https://cloud.githubusercontent.com/assets/883126/8344523/9fc3ffa4-1a97-11e5-9696-f63c5a0d10fd.png)
![screen shot 2015-06-24 at 5 19 31 pm](https://cloud.githubusercontent.com/assets/883126/8344524/9fc4ac2e-1a97-11e5-9e2c-ad3774838f4c.png)

ping @yyx990803

**Comment by yyx990803** [comment]
It seems to me it's more likely that the timeline force GC button doesn't always properly recollect DOM Nodes. Two reasons:

1. Similar Node count increase is found for almost all major frameworks you tested with this approach;
2. When comparing memory heap snapshots, no Node leaks were found. Steps:
  1. Create and delete one item (because Vue caches compilation/templates for the item)
  2. Take a snapshot
  3. Create N items, delete them all
  4. Take another snapshot
  5. Repeat 2~4 a few times
  6. Compare the snapshots (click the "Summary" dropdown and choose "Comparison")

**Comment by samccone** [comment]
Hi @yyx990803, thanks for getting back to me.

As to point one, I agree, almost all of the framework implementations do exhibit this behavior! Checkout the Backbone or the Marionette implementations, as they are the only ones I have found so far that do not leak. 
The goal of my research is to help TodoMVC implementation authors and framework authors to create tools and libraries that do not leak. Since the tooling around detecting memory leaks is quite immature, many people do not know how to find them. That is where I have been coming in to help.

Onto your main point that using the heap snapshot tool does not expose any leaking nodes. I have found that sometimes your have to dig a bit to find the nodes that are actually leaking depending on their depth in the graph, or expand what you consider a "node"

I have found the following, it looks like each time I run through my test this app implementation keeps attaching more pointers to the DOM which I **think** is causing the increase in the node count on each run through the test steps.

##### Start:
![screen shot 2015-06-26 at 4 16 28 pm](https://cloud.githubusercontent.com/assets/883126/8389159/e9c582d2-1c20-11e5-9186-b4e6e75d5e94.png)

##### Stop:
![screen shot 2015-06-26 at 4 16 34 pm](https://cloud.githubusercontent.com/assets/883126/8389165/f3846d1a-1c20-11e5-96e1-d2f8be3ce74f.png)


^ Looks like I can consistently leak 10 nodes ^ 

##### What are these ¿Objects¿ 

![screen shot 2015-06-26 at 4 18 38 pm](https://cloud.githubusercontent.com/assets/883126/8389167/fabbd2e4-1c20-11e5-95a4-2179e05cc4ae.png)

(and I think that string might be considered a "node" as well which would line up with the **10** leaking nodes



So poking into this object we can see how it points to a DOM node :smiling_imp: 

![screen shot 2015-06-26 at 4 27 11 pm](https://cloud.githubusercontent.com/assets/883126/8389182/32e5979a-1c21-11e5-9a3a-d0985e5b1831.png)


So I still do think there is a real leak or cycle that is preventing a clean GC.

----------------

As to 

> When recording timeline for several times, occasionally I find the Node count dropping below starting count after clicking GC button

I have seen this occasionally, and I do not have a good explanation for this behavior, perhaps @paulirish might have a good explanation for us.

Let me know what you think @yyx990803 !

**Comment by sindresorhus** [comment]
What's the next step for resolving this ticket?

**Comment by paulirish** [comment]
>> When recording timeline for several times, occasionally I find the Node count dropping below starting count after clicking GC button
> I have seen this occasionally, and I do not have a good explanation for this behavior, perhaps @paulirish might have a good explanation for us.

This is my read on the above scenario (no guarantees its right)

GC only kicks in when it has to.  Even if there are things it *could* clean it, it may not yet.. (This is starting to change as we're taking memory pressure heuristics and applying them around)

Anyhow, i imagine the node count was dropping below original count because GC just hadnt taken a swipe at the detached DOM nodes yet.

Relatedly, this issue triggered me to refactor this counter view. :)  
https://code.google.com/p/chromium/issues/detail?id=523697#c1
