### ISSUE TITLE
Running The Selenium Tests - Browser not opening.

### ISSUE THREAD

**Issue by defx** [tastejs/todomvc#1361]
This issue started as #1357 which was prematurely closed, possibly because the question wasn't clear enough.

I am able to run the server without any problems, but I get `Error: Unable to find application root, did you start your local server?`. The problem appears to be that the test browser isn't opening as expected. I've tried running with chrome, firefox and phantom (all with the same result) so it would appear that this isn't particular to chrome.

I regularly run other tests with selenium-webdriver without any issues. Any ideas?

**Comment by arthurvr** [comment]
> The problem appears to be that the test browser isn't opening as expected.

Honestly sounds more like an issue with your local setup then with our tests setup.

> This issue started as #1357 which was prematurely closed

Please don't create a second issue because you think the first one was "prematurely" closed. If we think it's worth it and you can show us concrete troubles with our setup we will be happy to re-open. Let's take all discussion to that issue.

**Comment by defx** [comment]
@arthurvr I agree that there must be something in my local setup that doesn't play nicely. Considering that I run Selenium tests regularly in various different project configurations without any issues whatsoever, I though perhaps you might be interested to help me figure it out.

**Comment by arthurvr** [comment]
> Let's take all discussion to that issue.
