### ISSUE TITLE
Does Todomvc benefit one framework over the other?

### ISSUE THREAD

**Issue by qqbbgm** [tastejs/todomvc#1373]
Just some random thoughts

-

todomvc is the defacto tool everybody decides what framework to use. I think it's too opinionated and benefits some choices over the others.

I think that because @samccone is a member of the marionette team, @addyosmani wrote a backbone book and is building polymer and dart, @passy works on twitter (flightjs), @sindresorhus on Aura.js, ...

framework war is big business so I think many todomvc examples get benefitted because of the companies they work for and for money.

when I see the team page I think @arthurvr and @stephenplusplus are the only ones that aren't involved with a framework's development....

**Comment by arthurvr** [comment]
The fact that we all have a *personal* opinion is unavoidable. Everybody has one. :wink:
    
Though I agree TodoMVC should be neutral, I think it is. TodoMVC is just a curation of example apps. We don't promote/benefit any of the frameworks.  It would actually be difficult to do so. How can you promote one framework over the other using an example app only? We don't state our opinion on the frameworks anywhere, we just curate example apps :)

We're a team and nobody makes non-trivial decisions on its own. Nearly every change that happens gets discussed, in public. Everybody is free to post their thoughts on any issue and decisions rarely ever get made without hearing other people's thoughts.

> I think that because @samccone is a member of the marionette team, @addyosmani wrote a backbone book and is building polymer and dart, @passy works on twitter (flightjs), @sindresorhus on Aura.js, ..

Passy works on a totally different team than Flight, Aura is dead since years and Addy doesn't work on Dart. He also hasn't done much backbone things lately... :wink:

**Comment by qqbbgm** [comment]
Okay Arthur. I'm glad you responded instead of somebody that actually works on a framework. Thanks for the answer.

So if I understand correctly the only one that seriously works on a framework is @addyosmani, which is your development lead. Kinda not neutral?

**Comment by arthurvr** [comment]
> So if I understand correctly the only one that seriously works on a framework is @addyosmani, which is your development lead. Kinda not neutral?

We're not benefiting Polymer (and any other framework!) in any way. We don't even have a Polymer 1.0 example :p

**Comment by qqbbgm** [comment]
I can't find Addy in the commit log except in https://github.com/tastejs/todomvc/commit/5eac92fe2d5f86a6c48f9e2c35c25799a500bc45. So you have a neutral team lead but he's only active in one example....

anyways I'll stop the discussion. I understand that there's a bunch of money involved in this and that you can't really respond honest.

**Comment by passy** [comment]
+1 to everything Arthur has said. Everyone has their own preference, but my employer has absolutely no influence on that whatsoever. For example, I don't use Flight for any of my personal projects.
