### ISSUE TITLE
Marionette example uses deprecated features

### ISSUE THREAD

**Issue by benmccormick** [tastejs/todomvc#1436]
The Backbone.Marionette example is currently making heavy use of modules, as well as using the wreqr application channel.  Both of these features have been deprecated by the Marionette team.

The recommended replacement for modules is to use a module loader (webpack + es6 seems to be popular with the Mn community, but could also be RequireJS/CommonJS etc).  For the app channel, the recommendation is to use the Wreqr or Backbone.Radio API independently of the application object.  Backbone.Radio is considered the best practice, so that would probably be the correct thing to include.

I have a working fork of the current example that I'd be happy to clean up and submit as a PR, but wanted to clarify one thing first.

Is using ES6 modules + webpack (could be precompiled so that users wouldn't need a compile step, and build task could be done through npm if they wanted to hack on it) to high a bar?  I notice that several of the frameworks that have that as a best practice (specifically Ember and React) are not using modules, while others (Aurelia, Angular2) are.  Would a PR for Mn based on webpack be acceptable?

If not, would commonJS be better, or is the preference for globals based solutions only?

**Comment by samccone** [comment]
@benmccormick pure JS (es5) without a compile step would be ideal at this point in time.

One of the goals of todomvc is to really keep things stripped down for the example so that anyone can read the source and understand it (not split up everything into 100 files and have a build phase).

While I am with you, commonjs or es6 modules or webpack are great ways to structure a real "application".. the todomvc example for marionette should serve to show how to write an "app" that leverages marionettes API in the simplest form (so globals is totally one way to do that).

Let me know what you think and any PR is 100% welcome :palm_tree:
