### ISSUE TITLE
Criteria for sunsetting abandoned/obscure MVC implementations

### ISSUE THREAD

**Issue by dmethvin** [tastejs/todomvc#1534]
As I've looked at fixing a few of the frameworks in #789 it's pretty clear that some of them are no longer  being actively developed. It might help TodoMVC to remove them. It would definitely help me close #789. :smiley_cat: 

I'm not sure what the procedure or criteria might be, but [dijon](https://github.com/creynders/dijon) and [serenadejs](https://github.com/elabs/serenade.js/tree/master) would be candidates from my perspective.

**Comment by dmethvin** [comment]
Looks like this is related to #845, perhaps a duplicate or subset.

**Comment by arthurvr** [comment]
We've been dropping one off once upon a time (https://github.com/tastejs/todomvc/issues/1317, https://github.com/tastejs/todomvc/issues/1219, https://github.com/tastejs/todomvc/issues/1173, ...) but I definitely agree we should be able to drop off some more things. Big updates like https://github.com/tastejs/todomvc/issues/1110 and https://github.com/tastejs/todomvc/issues/789 always take way to long just because some frameworks/apps aren't very much alive any more :imp:

> Looks like this is related to #845, perhaps a duplicate or subset.

Yeah, that issue is planned for the 1.4 release too (see https://github.com/tastejs/todomvc/issues/1362). Let's close this as a dupe :)

@dmethvin Thanks for all the work on TodoMVC lately by the way! :heart:

**Comment by addyosmani** [comment]
Just wanted to echo a further thank you for all of the hard work helping us with TodoMVC. Thanks @dmethvin! :tada:
