### ISSUE TITLE
New App: Preact + ES6

### ISSUE THREAD

**Issue by developit** [tastejs/todomvc#1535]
Hi there. I forked the React TodoMVC implementation, and converted it to ES6 + [Preact](http://git.io/preact) + Webpack.

I'm not familiar with the process for getting things added to the official demos list, so I just threw it in a standalone repo with its own demo.

**Repo:** https://github.com/developit/preact-todomvc
**Demo:** http://developit.github.io/preact-todomvc/

**Comment by samccone** [comment]
Hey @developit thanks for the issue here, Preact seems really interesting. As with all of the submissions we like to see a community around the libs. At this time is seems like Preact is still quite new. For now I am going to close this issue, and we can reopen when you feel like you have a sizeable userbase and a decent amount of iteration around the codebase.

Feel free however to add this example to our wiki in the meantime.

Thanks again!

**Comment by developit** [comment]
It might still be worthwhile to at least update the React example, since it's written in a style that is now considered deprecated.

**Comment by developit** [comment]
Added. https://github.com/tastejs/todomvc/wiki/Other-implementations#preact--es6

**Comment by steelbrain** [comment]
Bump

**Comment by developit** [comment]
What's the process for adding these btw @samccone? Do you link out to existing repos, or bundle them into this one?

**Comment by samccone** [comment]
@developit PR welcome :)

**Comment by developit** [comment]
hello sam i was possessed by a demon that stole all of my time between the december 6th 2016 and today but i have time now and will submit a pr

**Comment by flashdesignory** [comment]
Closing this, since we added a Preact example https://github.com/tastejs/todomvc/pull/2197

@developit - please feel free to open a follow up pr, if the merged example needs adjustments!
