### ISSUE TITLE
change angular.js to angular.min.js

### ISSUE THREAD

**Issue by anubhav7495** [tastejs/todomvc#1572]
In the Angular examples, the angular source used in not the minified version and it is 1mb in size. We must change it to use the angular.min.js file instead to improve page load time.

**Comment by passy** [comment]
We don't optimize for load time. This is a learning resource and we want people be able to jump right into the source.

**Comment by anubhav7495** [comment]
I think you misunderstood, i am not talking about minifying the whole source file, only using the angular.min.js instead of angular.js from the npm packages.

**Comment by samccone** [comment]
I think @passy 's point still stands, however @anubhav7495 if you are interested in making a "perf" version of the angular example checkout https://github.com/tastejs/todomvc/issues/1541

**Comment by passy** [comment]
@anubhav7495 In order to fully understand an implementation, you'll most likely check out the library/framework code, too. We want to retain the ability to insert breakpoints and study the execution flow for all apps - unless it's inherently impossible due to transpilation or a similar required build step.

**Comment by anubhav7495** [comment]
oh! i understand. I will take a look at making a perf version. Thanks
