### ISSUE TITLE
My library doesn't quite fit your format

### ISSUE THREAD

**Issue by fresheneesz** [tastejs/todomvc#1603]
I'd like to write a todo app for this using [Gem.js](https://github.com/Tixit/Gem.js), but it uses pure javascript and a different way to do styles than normal css. This would require me to translate index.html and base.css into Gem.js javascript. I want to make sure this is ok before I spend my time doing it. Is this ok?

**Comment by fresheneesz** [comment]
@samccone Thoughts? What do i do?

**Comment by arthurvr** [comment]
At this point, we wouldn't accept gem.js because it just doesn't have a userbase yet. We always wait for a framework to mature a bit before adding an example app. Thanks for the suggestion though! 

That said, if that's really required we'd definitely be willing to search for an alternative solution to bring in the HTML and CSS template.

**Comment by fresheneesz** [comment]
@arthurvr Fair enough. Out of curiosity, what metrics do you use to define "having a userbase"?
