### ISSUE TITLE
SapUI5 implementation broken

### ISSUE THREAD

**Issue by Frank683** [tastejs/todomvc#1688]
Hi,

the SapUI5 implementation of TodoMVC is broken:

![image](https://cloud.githubusercontent.com/assets/14088575/18233929/c4987776-72f5-11e6-9ef4-a70737d88334.png)

@akudev 

Maybe it would make sense to include a specific UI5 version from the CDN and not the latest one?

**Comment by passy** [comment]
We wanted to do this, but SAP had some licensing problems preventing us from doing that, IIRC.

**Comment by Frank683** [comment]
Ok, I don't know what's the exact licensing issue but in that case OpenUI5 (it also has its own CDN) may be an alternative?

Otherwise if you can't get the implementation to work why leave it online?

**Comment by addyosmani** [comment]
I would personally be in favor of us dropping the SapUI5 version and replacing with #1570.

**Comment by arthurvr** [comment]
> I would personally be in favor of us dropping the SapUI5 version and replacing with #1570.

👍 ! 

Would be cool if folks could help us review (and maybe update) that PR though, I don't really know enough about the framework to be able to do a proper review.

**Comment by akudev** [comment]
Umm... I don't think linking to a specific version of UI5 instead of "latest" would cause any licensing issues. We did not even have these specific version available until summer 2015, so this might be the reason why it was not done.

However, right now the sample seems to work fine (tested in Chrome, FF, IE), so this issue could be closed? (@Frank683)
(sorry for the lack of response, I was not in office since September)

**Comment by Frank683** [comment]
Issue can be closed because implementation works again.

**Comment by arthurvr** [comment]
Yeah, I'll close this, thanks :)
