### ISSUE TITLE
node_modules required?

### ISSUE THREAD

**Issue by TorzuoliH** [tastejs/todomvc#1839]
Given that every example project has its own `package.json`, is *node_modules* folder necessary in remote repository?

**Comment by FadySamirSadek** [comment]
You should add your node_modules folder to your .gitignore except the files that are being used by your example. You will always need to include todomvc-common and todomvc-app-css as dependencies. And since you will need the css from the todomvc-app-css it is necessary to have the node_modules folder.
Example for a package.json  from [app-spec.md](https://github.com/tastejs/todomvc/blob/master/app-spec.md):

```
{
  "private": true,
  "dependencies": {
    "backbone": "^1.1.2",
    "todomvc-app-css": "^1.0.0",
    "todomvc-common": "^1.0.1"
  }
}
```
You can find more info about dependency management and specs in[ app-spec.md ](https://github.com/tastejs/todomvc/blob/master/app-spec.md)

**Comment by FadySamirSadek** [comment]
@addyosmani  @samccone  This one can be closed
