### ISSUE TITLE
Migrate existing test suite to cypress.io

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1843]
Now that cypress.io is out of private beta and free for OSS I think now is a good time to start the effort to migrate our existing integration test suite over.

@brian-mann I know you have an old version that you ported a long time ago? Thoughts on opening an initial PR? We can take it from there.

Thanks!

**Comment by brian-mann** [comment]
Pinging @bahmutov to get his feedback. 

Not exactly sure what you're suggesting. TodoMVC tests are written in Selenium. Are you suggesting having a single port to Cypress as a reference? Or porting all existing tests over to it and no longer having Selenium?

**Comment by samccone** [comment]
I am proposing we delete the selenium tests (which are currently broken and have been for a long time) and replace them with cypress tests!

**Comment by bahmutov** [comment]
Hahaha we have this for your repo as one of our own internal issues! Completely agree, we can help with that. And this will find some  discrepancies between implementations- dom element presence vs visibility, different class names, missing features

**Comment by brian-mann** [comment]
Yeah there are idioms in Cypress that don't exist anywhere else (like waiting on XHR's for example).

I think we can have a discussion about us taking over maintaining the tests - since we have full time people that could be dedicated to this.

Specifically we'll need to work out:

- How to implement generic enough Cypress tests across all various TodoMVC implementations
- Take advantage of Cypress specific features for implementations that require them (like when backend servers are involved)
- Handle running in CI / possibly managing and introducing docker containers (?)
- Recording on our dashboard and handling the grouping of all of the implementations (?)
- Update the contributing guidelines for installing and running Cypress

All this is pretty do-able fairly quickly.

**Comment by brian-mann** [comment]
We've gone ahead and started the work on the fork today.

**Comment by vitalydmitriev1970** [comment]
You should fix your test job- it is broken
