### ISSUE TITLE
ES 6 example

### ISSUE THREAD

**Issue by avinashdvv** [tastejs/todomvc#2142]
https://github.com/tastejs/todomvc/blob/master/examples/vanilla-es6/src/store.js#L142 here why did we use the `this.find`, we can directly use the `this.getLocalStorage()` get the todos right?. To take this decision what is the idea behind of it

**Comment by kenliten** [comment]
One Responsibility, the find method has its own role here, and count too, so, in order to keep this pattern you need to keep things as simple as possible, another thing to have in mind is that in the future you could change the localStorage for a data base or a service, so, the less you've used localStorage, the easier will be to migrate to other technology.

Hope this to be helpful for you, dude, take your time to wonder things like this, you're in the right way.

| / Peace!

**Comment by FadySamirSadek** [comment]
please refer to #2216
